-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 46251c9523506b68419aefdf5ff6ff2fbc4506a4
    hooks:
    -   id: flake8
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-yaml
        exclude: vagga.yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: requirements-txt-fixer
