-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 63142f2d4ece8fd67cad3521c6e0c0f2bfef1c03
    hooks:
    -   id: flake8
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-yaml
        exclude: vagga.yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: requirements-txt-fixer
